version: '3'
services:
  frontend: 
    container_name: frontend
    image: boomika69/frend:latest   # from Docker Hub
    ports: 
      - "8080:80"   # internal port 80 mapped to 8080
    depends_on:
      - backend
      - mongo
    networks:
      - three-tier-net 

  backend:
    container_name: backend
    image: boomika69/bcend:latest   # from Docker Hub
    ports: 
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/schooldb
    depends_on:
      - mongo
    networks:
      - three-tier-net

  mongo:
    container_name: mongo-container
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - three-tier-net

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"   # external port
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - three-tier-net

volumes:
  mongo-data:

networks:
  three-tier-net:
    name: three-tier-net
    driver: bridge
